"""
Django settings for fAIth project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import logging
import os
from pathlib import Path


# Set up logging
logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(name)s: %(message)s')
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR.joinpath('subdir').
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY or SECRET_KEY == "CHANGE_ME_use_a_long_secret_key":
    raise ValueError("DJANGO_SECRET_KEY environment variable is not set or was set to the default value")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.getenv("DJANGO_DEBUG") or "").strip().lower() in ("1", "true", "yes")

ALLOWED_HOSTS = json.loads(str(os.getenv("DJANGO_ALLOWED_HOSTS") or '["127.0.0.1", "localhost"]').strip())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ai",
    "backend",
    "frontend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_asgi_lifespan.middleware.LifespanStateMiddleware"
]

ROOT_URLCONF = "fAIth.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fAIth.wsgi.application"
ASGI_APPLICATION = "fAIth.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

postgres_host = str(os.getenv("POSTGRES_HOST") or "postgres").strip()
postgres_port = str(os.getenv("POSTGRES_PORT") or "5432").strip()
postgres_user = str(os.getenv("POSTGRES_USER") or "faith_user").strip()
postgres_password = os.getenv("POSTGRES_PASSWORD")
postgres_database = str(os.getenv("POSTGRES_DATABASE") or "faith_db").strip()

if not postgres_password or postgres_password == "CHANGE_ME_use_a_strong_password":
    raise ValueError("POSTGRES_PASSWORD environment variable is not set or was set to the default value")

# If Postgres host is a valid URL, remove the protocol prefix to make it a valid Django database host URI
if postgres_host.startswith(("http://", "https://")):
    postgres_host = postgres_host.replace("http://", "").replace("https://", "")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': postgres_host,
        'PORT': postgres_port,
        'USER': postgres_user,
        'PASSWORD': postgres_password,
        'NAME': postgres_database
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.joinpath("staticfiles")
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

NINJA_DOCS_CONF = {
    "title": "fAIth API",
    "version": "1.0.0",
    "ui": "swagger"
}