# Generated by Django 5.2.5 on 2025-09-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbeddingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required. Human‑readable name of the embedding model.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from name if left blank. Must be unique.",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. Long-form description of the embedding model (capabilities, size, provider).",
                    ),
                ),
                (
                    "runner",
                    models.CharField(
                        choices=[
                            (
                                "hf_sentence_transformers",
                                "Hugging Face Sentence Transformers",
                            ),
                            ("llama_cpp_python", "Llama CPP Python"),
                            ("ollama", "Ollama"),
                            ("docker_model_runner", "Docker Model Runner"),
                        ],
                        help_text="The runner used to run the embedding model.",
                        max_length=255,
                    ),
                ),
                (
                    "model_repo",
                    models.CharField(
                        blank=True,
                        help_text="The repository of the embedding model. This is used to identify the embedding model in the runner.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="The ID of the embedding model. This is used to identify the embedding model in the runner.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the embedding model is active."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the embedding model was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the embedding model was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding Model",
                "verbose_name_plural": "Embedding Models",
                "ordering": ["name"],
            },
        ),
    ]
